trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>=4.3.0' 

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'FxConsole.sln' 

- task: MSBuild@1
  displayName: 'Build (configuration=$(buildConfiguration))'
  inputs:
    solution: 'FxConsole.sln'
    configuration: $(buildConfiguration) 

- task: CopyFiles@2
  inputs:
    contents: 'FxConsole/bin/$(buildConfiguration)/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)/FxConsole'

- task: PublishBuildArtifacts@1

